"use client";

import { useCallback, useEffect, useState } from "react";
import { FileCheck2, Plus, Trash2, UploadCloud } from "lucide-react";
import type { ScormPackage } from "@/types";
import { Button, PageHeader, Sheet, useConfirm } from "@/components/ui";
import { normalizeStandardsLaunchPath, validateStandardsFileName, validateStandardsManifestText, validateStandardsTitle } from "@/lib/validation/standards";

type Draft = { title: string; launchPath: string; status: ScormPackage["status"] };
const samples = [
  { label: "SCORM 1.2", fileName: "imsmanifest.xml", xml: '<manifest identifier="sample" version="1.2"><organizations><organization><title>Sample SCORM Course</title></organization></organizations><resources><resource identifier="r1" href="launch/index.html" /></resources></manifest>' },
  { label: "SCORM 2004", fileName: "imsmanifest.xml", xml: '<manifest identifier="sample" version="2004 4th Edition"><organizations><organization><title>Sample SCORM 2004 Course</title></organization></organizations><resources><resource identifier="r1" href="index.html" /></resources></manifest>' },
  { label: "xAPI", fileName: "tincan.xml", xml: '<tincan><activities><activity id="https://edsync.app/sample"><name>Sample xAPI Activity</name><launch lang="en-us">index.html</launch></activity></activities></tincan>' },
  { label: "cmi5", fileName: "cmi5.xml", xml: '<courseStructure><course><title>Sample cmi5 Course</title><au id="au-1"><title>Launch AU</title><url>au/index.html</url></au></course></courseStructure>' },
];

export default function AdminStandardsPage() {
  const [packages, setPackages] = useState<ScormPackage[]>([]);
  const [form, setForm] = useState({ fileName: "imsmanifest.xml", manifestText: "" });
  const [draft, setDraft] = useState<Draft>({ title: "", launchPath: "", status: "parsed" });
  const [editingId, setEditingId] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const confirm = useConfirm();
  const load = useCallback(async () => { try { const response = await fetch("/api/standards", { cache: "no-store" }); const payload = await response.json(); if (!response.ok || payload.error) throw new Error(payload.error || "Could not load packages."); setPackages(payload.data?.packages ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load packages."); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const run = async (body: Record<string, unknown>, success: string) => { setBusy(true); setError(""); try { const response = await fetch("/api/standards", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok || payload.error) throw new Error(payload.error || "Package could not be saved."); setNotice(success); await load(); return true; } catch (reason) { setError(reason instanceof Error ? reason.message : "Package could not be saved."); return false; } finally { setBusy(false); } };
  const create = (sample?: (typeof samples)[number]) => { setEditingId(null); setForm(sample ? { fileName: sample.fileName, manifestText: sample.xml } : { fileName: "imsmanifest.xml", manifestText: "" }); setOpen(true); };
  const edit = (item: ScormPackage) => { setEditingId(item.id); setDraft({ title: item.title, launchPath: item.launch_path ?? "", status: item.status }); setOpen(true); };
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); try { if (editingId) { validateStandardsTitle(draft.title); normalizeStandardsLaunchPath(draft.launchPath); } else { validateStandardsFileName(form.fileName); validateStandardsManifestText(form.manifestText); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Manifest is invalid."); return; } const ok = await run(editingId ? { action: "update", id: editingId, ...draft } : { action: "parse", ...form }, editingId ? "Package saved." : "Manifest parsed."); if (ok) setOpen(false); };
  const remove = async (item: ScormPackage) => { if (!await confirm({ title: `Delete ${item.title}?`, body: "The package record and its tenant link will be removed.", confirmLabel: "Delete package", danger: true })) return; await run({ action: "delete", id: item.id }, "Package deleted."); };
  const readFile = async (file?: File) => { if (!file) return; try { const text = await file.text(); setForm({ fileName: file.name, manifestText: text }); } catch { setError("Could not read the selected manifest."); } };

  return <div className="page-shell space-y-4"><PageHeader title="Standards packages" icon={FileCheck2} count={packages.length} actions={<Button variant="primary" onClick={() => create()}><Plus size={16} /> Parse manifest</Button>} />
    <p className="text-xs text-fg-muted">Parse SCORM, xAPI or cmi5 manifest XML. Package files and launch hosting require a separate storage step.</p>
    {error && <p role="alert" className="rounded-lg bg-danger-soft px-4 py-3 text-sm text-danger">{error}</p>}{notice && <p role="status" className="text-sm text-fg-muted">{notice}</p>}
    <div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase tracking-wide text-fg-faint">Templates</span>{samples.map((sample) => <button type="button" key={sample.label} onClick={() => create(sample)} className="rounded-full border border-line bg-surface px-3 py-1.5 text-xs font-medium text-fg-muted hover:border-accent hover:text-fg">{sample.label}</button>)}</div>
    <section className="card divide-y divide-line overflow-hidden">{packages.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 px-4 py-3 sm:flex-nowrap"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent-soft text-accent"><FileCheck2 size={17} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-fg">{item.title}</p><p className="truncate text-xs text-fg-muted">{item.package_type.replaceAll("_", " ")} · {item.launch_path || "No launch path"}</p></div><span className="rounded-full bg-surface-2 px-2 py-1 text-xs font-medium capitalize text-fg-muted">{item.status}</span><button type="button" className="rounded-md px-2 py-1.5 text-sm text-fg-muted hover:bg-surface-2" onClick={() => edit(item)}>Edit</button><button type="button" className="rounded-md p-2 text-fg-muted hover:bg-danger-soft hover:text-danger" onClick={() => void remove(item)} aria-label={`Delete ${item.title}`}><Trash2 size={16} /></button></div>)}{packages.length === 0 && <p className="px-4 py-8 text-center text-sm text-fg-muted">No parsed manifests yet.</p>}</section>
    <Sheet open={open} onClose={() => setOpen(false)} title={editingId ? "Edit package" : "Parse manifest"} description={editingId ? "Update the package record." : "Select an XML manifest or paste its contents."} size="lg" onSubmit={save} footer={<><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="primary" disabled={busy}>{busy ? "Saving…" : editingId ? "Save package" : "Parse manifest"}</Button></>}>
      {error && <p role="alert" className="mb-3 rounded-lg bg-danger-soft px-3 py-2 text-sm text-danger">{error}</p>}{editingId ? <div className="space-y-4"><label className="block space-y-1 text-sm font-medium text-fg">Title<input className="edsync-input w-full" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required /></label><label className="block space-y-1 text-sm font-medium text-fg">Launch path<input className="edsync-input w-full" value={draft.launchPath} onChange={(event) => setDraft({ ...draft, launchPath: event.target.value })} placeholder="launch/index.html" /></label><label className="block space-y-1 text-sm font-medium text-fg">Status<select className="edsync-input w-full" value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as ScormPackage["status"] })}><option value="uploaded">Uploaded</option><option value="parsed">Parsed</option><option value="error">Error</option><option value="archived">Archived</option></select></label></div> : <div className="space-y-4"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-line px-4 py-6 text-sm font-medium text-fg-muted hover:bg-surface-2"><UploadCloud size={18} /> Choose manifest XML<input type="file" accept=".xml,text/xml,application/xml" className="sr-only" onChange={(event) => void readFile(event.target.files?.[0])} /></label><label className="block space-y-1 text-sm font-medium text-fg">File name<input className="edsync-input w-full" value={form.fileName} onChange={(event) => setForm({ ...form, fileName: event.target.value })} required /></label><label className="block space-y-1 text-sm font-medium text-fg">Manifest XML<textarea className="edsync-input min-h-48 w-full font-mono text-xs" value={form.manifestText} onChange={(event) => setForm({ ...form, manifestText: event.target.value })} placeholder="Paste XML manifest" required /></label></div>}
    </Sheet>
  </div>;
}
