import { normalizePublicLanguage, type PublicLanguageName } from "./languages";

type AuthCopy = {
  account: string;
  accountStep: string;
  alreadyHaveAccount: string;
  back: string;
  checkEmail: string;
  checkingOrganization: string;
  chooseActiveOrganization: string;
  continue: string;
  createNew: string;
  creatingAccount: string;
  email: string;
  enterOrganization: string;
  fullName: string;
  individual: string;
  individualCopy: string;
  individualWorkspace: string;
  joinExisting: string;
  missingOrganization: string;
  newToEdSync: string;
  openPortal: string;
  organization: string;
  organizationCode: string;
  organizationCopy: string;
  organizationName: string;
  password: string;
  passwordPlaceholder: string;
  protectedPortals: string;
  role: string;
  roleStep: string;
  signingIn: string;
  spaceStep: string;
  ssoOptions: string;
  student: string;
  studentCopy: string;
  teacher: string;
  teacherCopy: string;
  useIndividual: string;
  welcomeBack: string;
  workspaceTitle: string;
  workspaceCopy: string;
};

const englishAuthCopy: AuthCopy = {
  account: "Account",
  accountStep: "3 Account",
  alreadyHaveAccount: "Already have an account?",
  back: "Back",
  checkEmail: "Check your email",
  checkingOrganization: "Checking organization...",
  chooseActiveOrganization: "Choose an active organization before continuing.",
  continue: "Continue",
  createNew: "Create new",
  creatingAccount: "Creating account...",
  email: "Email",
  enterOrganization: "Enter organization",
  fullName: "Full name",
  individual: "Individual",
  individualCopy: "Personal teacher or learner workspace.",
  individualWorkspace: "Individual workspace",
  joinExisting: "Join existing",
  missingOrganization: "No active organization found for that code yet.",
  newToEdSync: "New to EdSync?",
  openPortal: "Open portal",
  organization: "Organization",
  organizationCode: "Organization code",
  organizationCopy: "School, academy, company, or cohort.",
  organizationName: "Organization name",
  password: "Password",
  passwordPlaceholder: "Minimum 8 characters",
  protectedPortals: "Protected teacher, student, and admin portals.",
  role: "Role",
  roleStep: "2 Role",
  signingIn: "Signing in...",
  spaceStep: "1 Workspace",
  ssoOptions: "SSO options",
  student: "Student",
  studentCopy: "Join learning spaces, take lessons, track grades, and save progress.",
  teacher: "Teacher",
  teacherCopy: "Create courses, manage classes, grade work, and publish catalog items.",
  useIndividual: "Use as individual",
  welcomeBack: "Welcome back",
  workspaceTitle: "Enter your learning workspace.",
  workspaceCopy: "Choose an organization when your school or company manages access, or continue with your individual space.",
};

const authCopy: Record<PublicLanguageName, Partial<AuthCopy>> = {
  English: englishAuthCopy,
  Korean: {
    account: "계정",
    alreadyHaveAccount: "이미 계정이 있나요?",
    back: "뒤로",
    checkEmail: "이메일 확인",
    checkingOrganization: "조직 확인 중...",
    continue: "계속",
    createNew: "새로 만들기",
    email: "이메일",
    enterOrganization: "조직 입력",
    fullName: "이름",
    individual: "개인",
    individualWorkspace: "개인 작업 공간",
    joinExisting: "기존 조직 참여",
    missingOrganization: "해당 코드의 활성 조직이 없습니다.",
    newToEdSync: "EdSync가 처음인가요?",
    openPortal: "포털 열기",
    organization: "조직",
    organizationCode: "조직 코드",
    organizationName: "조직 이름",
    password: "비밀번호",
    role: "역할",
    signingIn: "로그인 중...",
    ssoOptions: "SSO 옵션",
    student: "학생",
    teacher: "교사",
    useIndividual: "개인으로 사용",
    welcomeBack: "다시 오신 것을 환영합니다",
  },
  Khmer: {
    account: "គណនី",
    alreadyHaveAccount: "មានគណនីរួចហើយ?",
    back: "ត្រឡប់ក្រោយ",
    checkEmail: "ពិនិត្យអ៊ីមែល",
    checkingOrganization: "កំពុងពិនិត្យអង្គការ...",
    continue: "បន្ត",
    createNew: "បង្កើតថ្មី",
    email: "អ៊ីមែល",
    enterOrganization: "បញ្ចូលអង្គការ",
    fullName: "ឈ្មោះពេញ",
    individual: "បុគ្គល",
    individualWorkspace: "កន្លែងធ្វើការផ្ទាល់ខ្លួន",
    joinExisting: "ចូលរួមអង្គការ",
    missingOrganization: "រកមិនឃើញអង្គការសកម្មសម្រាប់កូដនេះទេ។",
    newToEdSync: "ថ្មីសម្រាប់ EdSync?",
    openPortal: "បើកផតថល",
    organization: "អង្គការ",
    organizationCode: "កូដអង្គការ",
    organizationName: "ឈ្មោះអង្គការ",
    password: "ពាក្យសម្ងាត់",
    role: "តួនាទី",
    signingIn: "កំពុងចូល...",
    ssoOptions: "ជម្រើស SSO",
    student: "សិស្ស",
    teacher: "គ្រូ",
    useIndividual: "ប្រើជាបុគ្គល",
    welcomeBack: "សូមស្វាគមន៍មកវិញ",
  },
  Chinese: {
    account: "账户",
    alreadyHaveAccount: "已经有账户？",
    back: "返回",
    checkEmail: "检查邮箱",
    checkingOrganization: "正在检查组织...",
    continue: "继续",
    createNew: "新建",
    email: "邮箱",
    enterOrganization: "输入组织",
    fullName: "全名",
    individual: "个人",
    individualWorkspace: "个人工作区",
    joinExisting: "加入已有组织",
    missingOrganization: "没有找到该代码对应的有效组织。",
    newToEdSync: "第一次使用 EdSync？",
    openPortal: "打开门户",
    organization: "组织",
    organizationCode: "组织代码",
    organizationName: "组织名称",
    password: "密码",
    role: "角色",
    signingIn: "正在登录...",
    ssoOptions: "SSO 选项",
    student: "学生",
    teacher: "教师",
    useIndividual: "作为个人使用",
    welcomeBack: "欢迎回来",
  },
  Japanese: {
    account: "アカウント",
    alreadyHaveAccount: "すでにアカウントがありますか？",
    back: "戻る",
    checkEmail: "メールを確認",
    checkingOrganization: "組織を確認中...",
    continue: "続ける",
    createNew: "新規作成",
    email: "メール",
    enterOrganization: "組織を入力",
    fullName: "氏名",
    individual: "個人",
    individualWorkspace: "個人ワークスペース",
    joinExisting: "既存組織に参加",
    missingOrganization: "そのコードの有効な組織は見つかりません。",
    newToEdSync: "EdSync は初めてですか？",
    openPortal: "ポータルを開く",
    organization: "組織",
    organizationCode: "組織コード",
    organizationName: "組織名",
    password: "パスワード",
    role: "役割",
    signingIn: "サインイン中...",
    ssoOptions: "SSO オプション",
    student: "学生",
    teacher: "教師",
    useIndividual: "個人として使う",
    welcomeBack: "おかえりなさい",
  },
  Spanish: {
    account: "Cuenta",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    back: "Atrás",
    checkEmail: "Revisa tu correo",
    checkingOrganization: "Comprobando organización...",
    continue: "Continuar",
    createNew: "Crear nueva",
    creatingAccount: "Creando cuenta...",
    email: "Correo",
    enterOrganization: "Entrar a organización",
    fullName: "Nombre completo",
    individual: "Individual",
    individualCopy: "Espacio personal para enseñar o aprender.",
    individualWorkspace: "Espacio individual",
    joinExisting: "Unirse a existente",
    missingOrganization: "No se encontró una organización activa con ese código.",
    newToEdSync: "¿Nuevo en EdSync?",
    openPortal: "Abrir portal",
    organization: "Organización",
    organizationCode: "Código de organización",
    organizationCopy: "Escuela, academia, empresa o grupo.",
    organizationName: "Nombre de organización",
    password: "Contraseña",
    passwordPlaceholder: "Mínimo 8 caracteres",
    protectedPortals: "Portales protegidos para docentes, estudiantes y admin.",
    role: "Rol",
    roleStep: "2 Rol",
    signingIn: "Iniciando sesión...",
    spaceStep: "1 Espacio",
    ssoOptions: "Opciones SSO",
    student: "Estudiante",
    studentCopy: "Únete a espacios, toma lecciones, revisa notas y guarda progreso.",
    teacher: "Docente",
    teacherCopy: "Crea cursos, gestiona clases, califica y publica catálogo.",
    useIndividual: "Usar individualmente",
    welcomeBack: "Bienvenido de nuevo",
    workspaceTitle: "Entra a tu espacio de aprendizaje.",
    workspaceCopy: "Usa una organización si tu escuela o empresa gestiona el acceso, o continúa con tu espacio individual.",
  },
  French: {
    account: "Compte",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    back: "Retour",
    checkEmail: "Vérifiez votre e-mail",
    checkingOrganization: "Vérification de l'organisation...",
    continue: "Continuer",
    createNew: "Créer",
    email: "E-mail",
    enterOrganization: "Entrer une organisation",
    fullName: "Nom complet",
    individual: "Individuel",
    individualWorkspace: "Espace individuel",
    joinExisting: "Rejoindre",
    missingOrganization: "Aucune organisation active avec ce code.",
    newToEdSync: "Nouveau sur EdSync ?",
    openPortal: "Ouvrir le portail",
    organization: "Organisation",
    organizationCode: "Code organisation",
    organizationName: "Nom de l'organisation",
    password: "Mot de passe",
    role: "Rôle",
    signingIn: "Connexion...",
    ssoOptions: "Options SSO",
    student: "Étudiant",
    teacher: "Enseignant",
    useIndividual: "Utiliser en individuel",
    welcomeBack: "Bon retour",
  },
  Vietnamese: {
    account: "Tài khoản",
    alreadyHaveAccount: "Đã có tài khoản?",
    back: "Quay lại",
    checkEmail: "Kiểm tra email",
    checkingOrganization: "Đang kiểm tra tổ chức...",
    continue: "Tiếp tục",
    createNew: "Tạo mới",
    email: "Email",
    enterOrganization: "Nhập tổ chức",
    fullName: "Họ và tên",
    individual: "Cá nhân",
    individualWorkspace: "Không gian cá nhân",
    joinExisting: "Tham gia tổ chức",
    missingOrganization: "Không tìm thấy tổ chức hoạt động với mã này.",
    newToEdSync: "Mới dùng EdSync?",
    openPortal: "Mở cổng",
    organization: "Tổ chức",
    organizationCode: "Mã tổ chức",
    organizationName: "Tên tổ chức",
    password: "Mật khẩu",
    role: "Vai trò",
    signingIn: "Đang đăng nhập...",
    ssoOptions: "Tùy chọn SSO",
    student: "Học viên",
    teacher: "Giáo viên",
    useIndividual: "Dùng cá nhân",
    welcomeBack: "Chào mừng trở lại",
  },
  Thai: {
    account: "บัญชี",
    alreadyHaveAccount: "มีบัญชีอยู่แล้ว?",
    back: "กลับ",
    checkEmail: "ตรวจสอบอีเมล",
    checkingOrganization: "กำลังตรวจสอบองค์กร...",
    continue: "ต่อไป",
    createNew: "สร้างใหม่",
    email: "อีเมล",
    enterOrganization: "ป้อนองค์กร",
    fullName: "ชื่อเต็ม",
    individual: "ส่วนบุคคล",
    individualWorkspace: "พื้นที่ส่วนบุคคล",
    joinExisting: "เข้าร่วมองค์กร",
    missingOrganization: "ไม่พบองค์กรที่ใช้งานด้วยรหัสนี้",
    newToEdSync: "เพิ่งใช้ EdSync?",
    openPortal: "เปิดพอร์ทัล",
    organization: "องค์กร",
    organizationCode: "รหัสองค์กร",
    organizationName: "ชื่อองค์กร",
    password: "รหัสผ่าน",
    role: "บทบาท",
    signingIn: "กำลังเข้าสู่ระบบ...",
    ssoOptions: "ตัวเลือก SSO",
    student: "ผู้เรียน",
    teacher: "ครู",
    useIndividual: "ใช้แบบส่วนบุคคล",
    welcomeBack: "ยินดีต้อนรับกลับ",
  },
};

export function getPublicAuthCopy(language?: string | null): AuthCopy {
  return { ...englishAuthCopy, ...authCopy[normalizePublicLanguage(language)] };
}
