/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infra/cloudflare/wrangler.automation.jsonc --include-runtime=false --env-interface=AutomationEnv infra/cloudflare/automation-env.d.ts` (hash: 105e0add81be18fe519c0e5806422d77)
interface __BaseEnv_AutomationEnv {
	EDSYNC_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/automation");
	}
	interface Env extends __BaseEnv_AutomationEnv {}
}
interface AutomationEnv extends __BaseEnv_AutomationEnv {}
